"""Bundle experiments/tasks/*.json into web/tasks.js so the web app works from file:// without a server."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from cogbias.catalogue import BIASES  # noqa: E402
from cogbias.tasks import load_tasks  # noqa: E402


def main() -> None:
    tasks = list(load_tasks().values())
    biases = {b.id: {"name": b.name, "category": b.category, "definition": b.definition,
                     "mechanism": b.mechanism, "debiasing": b.debiasing, "references": b.references}
              for b in BIASES}
    out = ROOT / "web" / "tasks.js"
    out.write_text(
        "// Generated by scripts/build_web_tasks.py from experiments/tasks/*.json. Do not edit by hand.\n"
        f"window.COGBIAS_TASKS = {json.dumps(tasks, indent=2, ensure_ascii=False)};\n"
        f"window.COGBIAS_BIASES = {json.dumps(biases, indent=2, ensure_ascii=False)};\n",
        encoding="utf-8",
    )
    print(f"wrote {out} ({len(tasks)} tasks, {len(biases)} biases)")


if __name__ == "__main__":
    main()
