// Generated by scripts/build_web_tasks.py from experiments/tasks/*.json. Do not edit by hand.
window.COGBIAS_TASKS = [
  {
    "id": "asian_disease",
    "bias": "framing",
    "title": "The outbreak",
    "paradigm": "Tversky & Kahneman (1981) Asian disease problem, between-subjects framing",
    "design": "between",
    "intro": "Imagine a country is preparing for the outbreak of an unusual disease that is expected to kill 600 people. Two alternative programmes have been proposed. Which would you choose?",
    "conditions": {
      "gain": {
        "options": [
          {
            "id": "sure",
            "text": "Programme A: 200 people will be saved."
          },
          {
            "id": "gamble",
            "text": "Programme B: there is a 1/3 chance that 600 people will be saved, and a 2/3 chance that no one will be saved."
          }
        ]
      },
      "loss": {
        "options": [
          {
            "id": "sure",
            "text": "Programme C: 400 people will die."
          },
          {
            "id": "gamble",
            "text": "Programme D: there is a 1/3 chance that nobody will die, and a 2/3 chance that 600 people will die."
          }
        ]
      }
    },
    "scoring": {
      "type": "choice",
      "risky_option": "gamble"
    },
    "reference": {
      "gain_risky_rate": 0.28,
      "loss_risky_rate": 0.78
    },
    "debrief": "Programmes A and C are identical (200 live, 400 die), and so are B and D. In the original study 72% chose the sure option when it was framed as lives saved, but 78% chose the gamble when it was framed as deaths. You saw only one frame; the other frame is shown here so you can check whether your choice would have flipped."
  },
  {
    "id": "un_africa",
    "bias": "anchoring",
    "title": "The wheel of fortune",
    "paradigm": "Tversky & Kahneman (1974) anchoring with an obviously random anchor",
    "design": "between",
    "intro": "A random number generator has produced the number shown below. First say whether the true value is higher or lower than that number, then give your best estimate.",
    "question": "What percentage of the member states of the United Nations are African countries?",
    "conditions": {
      "low": {
        "anchor": 10
      },
      "high": {
        "anchor": 65
      }
    },
    "answer": 28,
    "scoring": {
      "type": "numeric",
      "min": 0,
      "max": 100
    },
    "reference": {
      "median_low": 25,
      "median_high": 45,
      "anchoring_index": 0.5
    },
    "debrief": "The number was random and carried no information, yet in the original study the group anchored on 10 estimated 25% while the group anchored on 65 estimated 45%. Today 54 of 193 UN members (28%) are African. Compare your estimate with the reference median for your anchor."
  },
  {
    "id": "cab_problem",
    "bias": "base_rate_neglect",
    "title": "The hit-and-run cab",
    "paradigm": "Kahneman & Tversky (1972) cab problem; Gigerenzer & Hoffrage (1995) frequency format",
    "design": "between",
    "conditions": {
      "probability": {
        "intro": "A cab was involved in a hit-and-run accident at night. Two cab companies, Green and Blue, operate in the city. 85% of the cabs are Green and 15% are Blue. A witness identified the cab as Blue. The court tested the witness under the same conditions and found that the witness correctly identified each colour 80% of the time.",
        "question": "What is the probability (0-100%) that the cab involved in the accident was Blue?"
      },
      "frequency": {
        "intro": "A cab was involved in a hit-and-run accident at night. Out of every 100 cabs in the city, 85 are Green and 15 are Blue. A witness identified the cab as Blue. When tested, the witness correctly identified the colour of 80 out of every 100 cabs, and got the other 20 wrong.",
        "question": "Out of 100 accidents like this one where the witness says 'Blue', how many involved a Blue cab? Give your answer as a number from 0 to 100."
      }
    },
    "answer": 41,
    "scoring": {
      "type": "numeric",
      "min": 0,
      "max": 100
    },
    "reference": {
      "modal_answer_probability": 80,
      "bayesian": 41
    },
    "debrief": "Of 100 cabs, 15 are Blue and the witness gets 12 of them right; 85 are Green and the witness wrongly calls 17 of them Blue. So when the witness says Blue, 12 of 29 cases (41%) are really Blue. Most people answer around 80% because they use the witness's reliability and ignore the base rate."
  },
  {
    "id": "linda",
    "bias": "conjunction",
    "title": "Linda",
    "paradigm": "Tversky & Kahneman (1983) conjunction fallacy",
    "design": "within",
    "intro": "Linda is 31 years old, single, outspoken and very bright. She majored in philosophy. As a student she was deeply concerned with issues of discrimination and social justice, and also participated in anti-nuclear demonstrations.",
    "question": "Which is more probable?",
    "options": [
      {
        "id": "teller",
        "text": "Linda is a bank teller."
      },
      {
        "id": "teller_feminist",
        "text": "Linda is a bank teller and is active in the feminist movement."
      }
    ],
    "scoring": {
      "type": "choice",
      "correct": "teller"
    },
    "reference": {
      "fallacy_rate": 0.85
    },
    "debrief": "Every feminist bank teller is a bank teller, so the second option can never be more probable than the first. 85% of participants nevertheless chose it, because the added detail makes the description more representative of Linda."
  },
  {
    "id": "wason",
    "bias": "confirmation",
    "title": "Four cards",
    "paradigm": "Wason (1968) selection task",
    "design": "within",
    "intro": "Each card has a number on one side and a colour on the other. You are told: 'If a card shows an even number on one face, then its opposite face is blue.'",
    "question": "Which card(s) must you turn over to test whether the rule is true? Select all that apply.",
    "options": [
      {
        "id": "3",
        "text": "3"
      },
      {
        "id": "8",
        "text": "8"
      },
      {
        "id": "blue",
        "text": "Blue"
      },
      {
        "id": "red",
        "text": "Red"
      }
    ],
    "scoring": {
      "type": "multi",
      "correct": [
        "8",
        "red"
      ]
    },
    "reference": {
      "correct_rate": 0.1
    },
    "debrief": "Only the 8 (an even number could hide a non-blue face) and the Red card (it could hide an even number) can falsify the rule. Turning the Blue card cannot: the rule says nothing about what is behind blue. Fewer than 10% choose 8 and Red; most choose 8 and Blue, looking for confirmation rather than refutation."
  },
  {
    "id": "trivia",
    "bias": "overconfidence",
    "title": "How sure are you?",
    "paradigm": "Two-alternative general-knowledge calibration (Lichtenstein & Fischhoff 1977)",
    "design": "within",
    "intro": "Answer each question, then say how confident you are that your answer is right (50% = a coin flip, 100% = certain).",
    "items": [
      {
        "q": "Which is longer?",
        "a": "Amazon River",
        "b": "Nile River",
        "correct": "b"
      },
      {
        "q": "Which city is further north?",
        "a": "Rome",
        "b": "New York",
        "correct": "a"
      },
      {
        "q": "Which has more people?",
        "a": "Nigeria",
        "b": "Russia",
        "correct": "a"
      },
      {
        "q": "Which is heavier?",
        "a": "A litre of water",
        "b": "A litre of olive oil",
        "correct": "a"
      },
      {
        "q": "Which was invented first?",
        "a": "The telephone",
        "b": "The typewriter",
        "correct": "b"
      },
      {
        "q": "Which country has more time zones?",
        "a": "France",
        "b": "United States",
        "correct": "a"
      },
      {
        "q": "Which planet has more moons?",
        "a": "Jupiter",
        "b": "Saturn",
        "correct": "b"
      },
      {
        "q": "Which is older?",
        "a": "Oxford University",
        "b": "The Aztec Empire",
        "correct": "a"
      },
      {
        "q": "Which is larger by area?",
        "a": "Greenland",
        "b": "Australia",
        "correct": "b"
      },
      {
        "q": "Which is closer to the equator?",
        "a": "Miami",
        "b": "Cairo",
        "correct": "a"
      }
    ],
    "scoring": {
      "type": "calibration"
    },
    "reference": {
      "typical_overconfidence": 0.15
    },
    "debrief": "Well-calibrated judges are right 70% of the time when they say '70%'. Most people are right about 15 percentage points less often than their confidence suggests, and the gap grows for harder questions."
  },
  {
    "id": "sunk_cost",
    "bias": "sunk_cost",
    "title": "Two ski trips",
    "paradigm": "Arkes & Blumer (1985) ski-trip scenario",
    "design": "within",
    "intro": "You paid $100 for a weekend ski trip to Michigan. Weeks later you paid $50 for a ski trip to Wisconsin. You think you will enjoy Wisconsin more. Then you notice both trips are on the same weekend. The tickets are non-refundable and cannot be resold. You must choose one.",
    "question": "Which trip do you take?",
    "options": [
      {
        "id": "michigan",
        "text": "The $100 Michigan trip"
      },
      {
        "id": "wisconsin",
        "text": "The $50 Wisconsin trip (the one you expect to enjoy more)"
      }
    ],
    "scoring": {
      "type": "choice",
      "correct": "wisconsin"
    },
    "reference": {
      "fallacy_rate": 0.54
    },
    "debrief": "The $150 is spent whichever trip you take, so only future enjoyment should matter. 54% of participants nonetheless chose the more expensive, less enjoyable trip to avoid 'wasting' more money."
  }
];
window.COGBIAS_BIASES = {
  "framing": {
    "name": "Framing effect",
    "category": "Prospect theory / reference dependence",
    "definition": "Logically equivalent descriptions of the same options lead to different choices depending on whether outcomes are described as gains or losses.",
    "mechanism": "Outcomes are evaluated relative to a reference point. The value function is concave for gains (risk aversion) and convex for losses (risk seeking), so a 'lives saved' frame favours the sure option while a 'lives lost' frame favours the gamble.",
    "debiasing": [
      "Re-describe every option in both a gain and a loss frame before deciding.",
      "Convert outcomes to a common absolute scale (e.g. expected lives, expected money).",
      "Ask: 'would I choose differently if the same facts were worded the other way?'"
    ],
    "references": [
      "Tversky, A., & Kahneman, D. (1981). The framing of decisions and the psychology of choice. Science, 211, 453-458.",
      "Kahneman, D., & Tversky, A. (1979). Prospect theory: An analysis of decision under risk. Econometrica, 47, 263-291."
    ]
  },
  "loss_aversion": {
    "name": "Loss aversion",
    "category": "Prospect theory / reference dependence",
    "definition": "Losses loom larger than equivalent gains; a loss of X hurts roughly twice as much as a gain of X pleases.",
    "mechanism": "The prospect-theory value function is steeper for losses than for gains (loss-aversion coefficient lambda ~ 2.25), so symmetric gambles look unattractive.",
    "debiasing": [
      "Evaluate decisions as a portfolio of repeated choices, not one-off gambles ('broad bracketing').",
      "Pre-commit to decision rules (e.g. stop-loss) before emotions are engaged.",
      "Explicitly compute expected value and compare with the felt reluctance."
    ],
    "references": [
      "Tversky, A., & Kahneman, D. (1992). Advances in prospect theory: Cumulative representation of uncertainty. Journal of Risk and Uncertainty, 5, 297-323.",
      "Kahneman, D., Knetsch, J. L., & Thaler, R. H. (1990). Experimental tests of the endowment effect and the Coase theorem. Journal of Political Economy, 98, 1325-1348."
    ]
  },
  "anchoring": {
    "name": "Anchoring and insufficient adjustment",
    "category": "Heuristics of judgement",
    "definition": "Numerical estimates are pulled toward an initial value (the anchor), even when the anchor is arbitrary or irrelevant.",
    "mechanism": "People start from the anchor and adjust until they reach a plausible range, but adjustment stops too early. Anchors also prime anchor-consistent knowledge (selective accessibility).",
    "debiasing": [
      "Generate your own estimate before seeing any number.",
      "'Consider the opposite': list reasons the anchor may be too high AND too low.",
      "Use base rates and reference classes rather than adjusting from a given figure."
    ],
    "references": [
      "Tversky, A., & Kahneman, D. (1974). Judgment under uncertainty: Heuristics and biases. Science, 185, 1124-1131.",
      "Jacowitz, K. E., & Kahneman, D. (1995). Measures of anchoring in estimation tasks. Personality and Social Psychology Bulletin, 21, 1161-1166.",
      "Mussweiler, T., Strack, F., & Pfeiffer, T. (2000). Overcoming the inevitable anchoring effect: Considering the opposite compensates for selective accessibility. PSPB, 26, 1142-1150."
    ]
  },
  "confirmation": {
    "name": "Confirmation bias",
    "category": "Belief formation",
    "definition": "The tendency to search for, interpret, and remember information in a way that confirms existing beliefs.",
    "mechanism": "Positive test strategy in hypothesis testing; asymmetric scrutiny of confirming vs disconfirming evidence; motivated reasoning that protects identity-relevant beliefs.",
    "debiasing": [
      "Actively seek disconfirming evidence; ask 'what would change my mind?'",
      "Assign a devil's advocate or run a pre-mortem.",
      "Weight evidence by its diagnosticity (likelihood ratio), not by whether it agrees with you."
    ],
    "references": [
      "Wason, P. C. (1968). Reasoning about a rule. Quarterly Journal of Experimental Psychology, 20, 273-281.",
      "Nickerson, R. S. (1998). Confirmation bias: A ubiquitous phenomenon in many guises. Review of General Psychology, 2, 175-220.",
      "Lord, C. G., Ross, L., & Lepper, M. R. (1979). Biased assimilation and attitude polarization. JPSP, 37, 2098-2109."
    ]
  },
  "base_rate_neglect": {
    "name": "Base-rate neglect",
    "category": "Heuristics of judgement (representativeness)",
    "definition": "Ignoring the prior probability of an event when given specific, case-based information.",
    "mechanism": "Judgement by representativeness: how similar the case looks to the category replaces Bayesian combination of prior and likelihood.",
    "debiasing": [
      "Translate probabilities into natural frequencies ('out of 1,000 people...').",
      "Always ask for the base rate before evaluating the specific evidence.",
      "Use the 'outside view': start from the reference class, then adjust."
    ],
    "references": [
      "Kahneman, D., & Tversky, A. (1973). On the psychology of prediction. Psychological Review, 80, 237-251.",
      "Gigerenzer, G., & Hoffrage, U. (1995). How to improve Bayesian reasoning without instruction: Frequency formats. Psychological Review, 102, 684-704.",
      "Bar-Hillel, M. (1980). The base-rate fallacy in probability judgments. Acta Psychologica, 44, 211-233."
    ]
  },
  "conjunction": {
    "name": "Conjunction fallacy",
    "category": "Heuristics of judgement (representativeness)",
    "definition": "Judging a conjunction (A and B) as more probable than one of its constituents (A).",
    "mechanism": "A detailed, representative story feels more likely than a sparse one, although every added detail can only lower probability.",
    "debiasing": [
      "Check the extension rule: P(A and B) <= P(A).",
      "Ask in frequencies: 'of 100 people like Linda, how many are bank tellers? how many are feminist bank tellers?'"
    ],
    "references": [
      "Tversky, A., & Kahneman, D. (1983). Extensional versus intuitive reasoning: The conjunction fallacy in probability judgment. Psychological Review, 90, 293-315."
    ]
  },
  "availability": {
    "name": "Availability heuristic",
    "category": "Heuristics of judgement",
    "definition": "Estimating frequency or probability by how easily examples come to mind.",
    "mechanism": "Ease of retrieval is used as a proxy for frequency; vivid, recent or emotional events are retrieved more easily.",
    "debiasing": [
      "Look up the statistics instead of relying on recall.",
      "Notice when an example is memorable because it is unusual."
    ],
    "references": [
      "Tversky, A., & Kahneman, D. (1973). Availability: A heuristic for judging frequency and probability. Cognitive Psychology, 5, 207-232.",
      "Lichtenstein, S., Slovic, P., Fischhoff, B., Layman, M., & Combs, B. (1978). Judged frequency of lethal events. JEP: Human Learning and Memory, 4, 551-578."
    ]
  },
  "overconfidence": {
    "name": "Overconfidence (miscalibration)",
    "category": "Metacognition",
    "definition": "Subjective confidence systematically exceeds objective accuracy, especially for hard questions.",
    "mechanism": "Confidence tracks the coherence of the story we can tell, not the quantity or quality of evidence (WYSIATI).",
    "debiasing": [
      "Keep a calibration log and score predictions (Brier score).",
      "Run a pre-mortem: 'assume the plan failed - why?'",
      "Widen interval estimates deliberately; use the outside view."
    ],
    "references": [
      "Lichtenstein, S., Fischhoff, B., & Phillips, L. D. (1982). Calibration of probabilities. In Kahneman, Slovic & Tversky (Eds.), Judgment under uncertainty.",
      "Moore, D. A., & Healy, P. J. (2008). The trouble with overconfidence. Psychological Review, 115, 502-517.",
      "Klein, G. (2007). Performing a project premortem. Harvard Business Review, 85, 18-19."
    ]
  },
  "sunk_cost": {
    "name": "Sunk-cost fallacy",
    "category": "Prospect theory / reference dependence",
    "definition": "Continuing an endeavour because of resources already invested, although only future costs and benefits should matter.",
    "mechanism": "Abandoning the project would 'realise' the loss; loss aversion and a desire not to appear wasteful keep people escalating commitment.",
    "debiasing": [
      "Ask: 'If I were deciding fresh today, with no history, what would I choose?'",
      "Separate the decision-maker from the person who made the original investment."
    ],
    "references": [
      "Arkes, H. R., & Blumer, C. (1985). The psychology of sunk cost. Organizational Behavior and Human Decision Processes, 35, 124-140.",
      "Staw, B. M. (1976). Knee-deep in the big muddy. Organizational Behavior and Human Performance, 16, 27-44."
    ]
  },
  "hindsight": {
    "name": "Hindsight bias",
    "category": "Memory and metacognition",
    "definition": "After an outcome is known, people believe they 'knew it all along' and overestimate how predictable it was.",
    "mechanism": "Outcome knowledge is integrated into memory and cannot be un-known; the past is reconstructed as more inevitable than it seemed.",
    "debiasing": [
      "Record forecasts and reasoning before outcomes are known (decision journal).",
      "Judge decisions by process and information available at the time, not by outcome."
    ],
    "references": [
      "Fischhoff, B. (1975). Hindsight is not equal to foresight. JEP: Human Perception and Performance, 1, 288-299.",
      "Roese, N. J., & Vohs, K. D. (2012). Hindsight bias. Perspectives on Psychological Science, 7, 411-426."
    ]
  },
  "status_quo": {
    "name": "Status-quo and default bias",
    "category": "Prospect theory / reference dependence",
    "definition": "A preference for the current state of affairs; defaults are chosen far more often than alternatives.",
    "mechanism": "The status quo is the reference point, so any change is coded as a mix of gains and losses, and losses loom larger.",
    "debiasing": [
      "Treat 'do nothing' as an active option and evaluate it like the others.",
      "Design defaults deliberately (choice architecture)."
    ],
    "references": [
      "Samuelson, W., & Zeckhauser, R. (1988). Status quo bias in decision making. Journal of Risk and Uncertainty, 1, 7-59.",
      "Johnson, E. J., & Goldstein, D. (2003). Do defaults save lives? Science, 302, 1338-1339."
    ]
  },
  "dunning_kruger": {
    "name": "Dunning-Kruger effect",
    "category": "Metacognition",
    "definition": "Low performers overestimate their ability because the skills needed to perform well are the same skills needed to judge performance.",
    "mechanism": "Metacognitive deficit plus regression to the mean in self-assessment; everybody's estimates are pulled toward 'above average'.",
    "debiasing": [
      "Seek objective feedback and external benchmarks.",
      "Learn the domain's failure modes: skill improves calibration."
    ],
    "references": [
      "Kruger, J., & Dunning, D. (1999). Unskilled and unaware of it. JPSP, 77, 1121-1134."
    ]
  }
};
